### ISSUE TITLE
macOS 5.2.1/5.3.0 build error: userContentController must be public

### ISSUE THREAD

**Issue by arrrrny** [arrrrny/zikzak_inappwebview#312]
## Build Error

```
InAppWebView.swift:2318:10: error: method 'userContentController(_:didReceive:)' must be declared public because it matches a requirement in public protocol 'WKScriptMessageHandler'
```

## Versions Affected
- zikzak_inappwebview_macos 5.2.1
- zikzak_inappwebview_macos 5.3.0

## Expected
The `userContentController(_:didReceive:)` method in `InAppWebView.swift` should be declared `public` so it can satisfy the `WKScriptMessageHandler` protocol requirement when the class is used as a public delegate.

## Context
This was introduced in PR #310 (fix/309-macos-domexception-crash) which added the `userContentController(_:didReceive:)` method for defensive deserialization. The method needs the `public` access modifier to match the protocol requirement.
